# Generated by Django 5.0.6 on 2024-06-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='j',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_image',
            field=models.ImageField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
    ]
