# Generated by Django 5.0.6 on 2024-06-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_favorite_product_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='collections', to='products.category')),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Collections',
        ),
    ]
