# Generated by Django 5.0.6 on 2024-06-25 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_collection_delete_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.collection'),
        ),
    ]
