# Generated by Django 5.0.6 on 2024-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_collection_collection_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="collection_images"
            ),
        ),
    ]
